version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
      timezone: Asia/Tokyo
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      prod:
        dependency-type: production
      dev:
        dependency-type: development
    commit-message:
      prefix: "chore"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
      timezone: Asia/Tokyo
    commit-message:
      prefix: "chore"
